// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHSQElp8MrDcaUS7tcur4qqGUljYqQV4',
    appId: '1:925808342421:web:fc5f37dd066dcb1f07329c',
    messagingSenderId: '925808342421',
    projectId: 'frambit-io',
    authDomain: 'frambit-io.firebaseapp.com',
    databaseURL: 'https://frambit-io-default-rtdb.firebaseio.com',
    storageBucket: 'frambit-io.appspot.com',
    measurementId: 'G-C716027QCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFF0_kcDBhDzy-HubZK7sWgVdEaffBpS4',
    appId: '1:925808342421:android:1bdc878c59c560e007329c',
    messagingSenderId: '925808342421',
    projectId: 'frambit-io',
    databaseURL: 'https://frambit-io-default-rtdb.firebaseio.com',
    storageBucket: 'frambit-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNHUR9AE7arTAwAuaLAsKG1gGxfQpvMg',
    appId: '1:925808342421:ios:bab51c0fd02e2df907329c',
    messagingSenderId: '925808342421',
    projectId: 'frambit-io',
    databaseURL: 'https://frambit-io-default-rtdb.firebaseio.com',
    storageBucket: 'frambit-io.appspot.com',
    androidClientId: '925808342421-9tiv6t9jlo2665jqv0t5i8jkuibgulue.apps.googleusercontent.com',
    iosClientId: '925808342421-2rl1h14l58vmptj78ofmejkllk0or5pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHSQElp8MrDcaUS7tcur4qqGUljYqQV4',
    appId: '1:925808342421:web:f6e02bd85538b52407329c',
    messagingSenderId: '925808342421',
    projectId: 'frambit-io',
    authDomain: 'frambit-io.firebaseapp.com',
    databaseURL: 'https://frambit-io-default-rtdb.firebaseio.com',
    storageBucket: 'frambit-io.appspot.com',
    measurementId: 'G-QNB5BHRSPM',
  );
}
